Remove requiring changes to the OpenProject core
btey/openproject-gitlab-integration pull request #6
Opened 2022-02-14 12:46 UTC by oliverguenther

I've taken a look at your plugin, and seen that you right now require changes to the OpenProject core for the plugin to work.

While right now we don't have a solution for extending paths to the frontend APIv3 service (I'll look into that!), you can avoid the second part with adding a patch/include for work packages.

For the first part, instead of requiring users to extend the path, you can simply build the path yourself until we can provide you with a more sane API to extend the APIv3Service.

I also removed some relative import paths that prevent the plugin from building correctly when the plugin is linked. I'd recommend that if you work with the plugin, you do frontend work with an IDE/VS Code from within the linked frontend, as there it will pick up the tsconfig paths mapping and make importing work as expected.

The reasoning behind this is written up here https://github.com/opf/openproject-proto_plugin#frontend-linking. It's a bit unfortunate but Angular CLI just doesn't provide us with any means (that I know) to have a linked plugin  build working without such a symlink construction.

Let me know what you think! You can reach out to me at o.guenther@openproject.com or @o.guenther:openproject.org on matrix

2022-02-14 21:47 UTC, btey commented
Hi @oliverguenther!

I tested the PR and works great. I will merge it for sure. Only the change from "APIV3Service" to lowercase "ApiV3Service" is generating an error because in the current code (version 12.0.7), the file "core-app/core/apiv3/api-v3.service" contains the class in uppercase. Therefore, when compiling the assets it generates this error:

```
./src/app/features/plugins/linked/openproject-gitlab_integration/tab-mrs/tab-mrs.component.ts:40:70-82 - Error: export 'ApiV3Service' (imported as 'ApiV3Service') was not found in 'core-app/core/apiv3/api-v3.service' (possible exports: APIV3Service)

./src/app/features/plugins/linked/openproject-gitlab_integration/tab-mrs/tab-mrs.component.ts:40:102-114 - Error: export 'ApiV3Service' (imported as 'ApiV3Service') was not found in 'core-app/core/apiv3/api-v3.service' (possible exports: APIV3Service)
```

But restoring to uppercase, work perfectly. I have seen that in the openproject development branch you already have it changed to lowercase. Surely that's why it's like this in the PR. If that's okay for you, for now, I can leave it in uppercase just to work with the current version, and when you release the change it can be done here as well.

Thank you very much @oliverguenther for this PR!

2022-02-14 21:59 UTC, btey requested changes

2022-02-14 21:59 UTC, btey commented on frontend/module/tab-mrs/tab-mrs.component.ts
> +import {ApiV3Service} from "core-app/core/apiv3/api-v3.service";
```suggestion
import {APIV3Service} from "core-app/core/apiv3/api-v3.service";
```

2022-02-14 21:59 UTC, btey commented on frontend/module/tab-mrs/tab-mrs.component.ts
> +    readonly apiV3Service:ApiV3Service,
```suggestion
    readonly apiV3Service:APIV3Service,
```

2022-02-15 07:08 UTC, oliverguenther commented
> But restoring to uppercase, work perfectly. I have seen that in the openproject development branch you already have it changed to lowercase. Surely that's why it's like this in the PR. If that's okay for you, for now, I can leave it in uppercase just to work with the current version, and when you release the change it can be done here as well.

Good catch! Yes I was working with the dev version, so the import was corrected automatically in my IDE. That's something you'll have to address when you update your dev version of the plugin.

2022-02-15 14:16 UTC, merged